### ISSUE TITLE
Alterar as rotas com parâmetros id por alguma característica da classe a que ele responde.

### ISSUE THREAD

**Issue by JairAssisDev** [JairAssisDev/CRM-HealthLink#12]
GET
[/crmhealthlink/api/doctor/exams/{idDoctor}](http://localhost:8080/swagger-ui/index.html#/Doctor%20API/findAllexams_1)
Obtém todas os enxames que o Doutor fez
GET
[/crmhealthlink/api/doctor/exams/patinet/{patientId}](http://localhost:8080/swagger-ui/index.html#/Doctor%20API/findAllPatientExams)
Obtém todas os enxames que o pacente fez
GET
[/crmhealthlink/api/doctor/appointment/{doctorId}](http://localhost:8080/swagger-ui/index.html#/Doctor%20API/findAll_1)
Obtém todas as Consultas atribidas ao doutor
[Employee API](http://localhost:8080/swagger-ui/index.html#/Employee%20API)
API para gestão de funcionários
GET
[/crmhealthlink/api/employee/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/getEmployeeById)
Obtém um funcionário pelo ID
PUT
[/crmhealthlink/api/employee/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/updateEmployee)
Atualiza um funcionário pelo ID
PUT
[/crmhealthlink/api/employee/paciente/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/updateEmployee_1)
Atualiza um Paciente
DELETE
[/crmhealthlink/api/employee/paciente/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/deletePacinet)
Remove um Paciente pelo ID
GET
[/crmhealthlink/api/employee/doctor/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/getDoctorById)
Obtém um médico pelo ID
PUT
[/crmhealthlink/api/employee/doctor/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/updateDoctor)
Atualiza um médico pelo ID
POST
[/crmhealthlink/api/employee/doctor/{managerid}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/createDoctor)
Cria um novo médico
GET
[/crmhealthlink/api/employee/getpaciente/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/getPatientById)
Obtém um Paciente pelo ID
[Patient API](http://localhost:8080/swagger-ui/index.html#/Patient%20API)
API para gestão de Pacientes
GET
[/crmhealthlink/api/patient/exams/{id}](http://localhost:8080/swagger-ui/index.html#/Patient%20API/findAllexams)
Obtém todas os enxames do pacente
GET
[/crmhealthlink/api/patient/appointments/{id}](http://localhost:8080/swagger-ui/index.html#/Patient%20API/findAllAppointments)
Obtém todas as Consultas do pacente

[Appointment API](http://localhost:8080/swagger-ui/index.html#/Appointment%20API)
API para gestão de Consultas
GET
[/crmhealthlink/api/appointment/{id}](http://localhost:8080/swagger-ui/index.html#/Appointment%20API/getAppointmentId)
Obtém uma Consulta pelo ID
PUT
[/crmhealthlink/api/appointment/{id}](http://localhost:8080/swagger-ui/index.html#/Appointment%20API/update)
Atualiza uma Consulta
DELETE
[/crmhealthlink/api/appointment/{id}](http://localhost:8080/swagger-ui/index.html#/Appointment%20API/delete)
Remove uma Consulta pelo ID

**Comment by JairAssisDev** [comment]
Alterar as rotas com parâmetros id por alguma característica da classe a que ele responde.

**Comment by JairAssisDev** [comment]
Refatoração: Atualiza a identificação do paciente de id para nome e email nos endpoints

**Comment by JairAssisDev** [comment]
Refatoração: Atualiza identificação de paciente e doutor (crm, nome e email) no DoctorController

**Comment by JairAssisDev** [comment]
Refatora código separando `DoctorController` e `AppointmentController` para melhor modularidade e organização

- Move operações de consulta (`Appointment`) para `AppointmentController`, deixando `DoctorController` focado em operações de médicos.
- Implementa DTOs específicos para criação (`AppointmentCreateDto`) e busca por ID (`AppointmentGetDto`), facilitando a manipulação dos dados.
- Adiciona documentação com Swagger para maior clareza dos endpoints e simplificação da integração com outros serviços.
- Melhora a reutilização de serviços e mapeadores, promovendo um código mais limpo e manutenível.

Essa refatoração melhora a estrutura e facilita a expansão futura das funcionalidades da API.

**Comment by JairAssisDev** [comment]
[Employee API](http://localhost:8080/swagger-ui/index.html#/Employee%20API)
API para gestão de funcionários



GET
[/api/employee/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/getEmployeeById)
Obtém um funcionário pelo ID


PUT
[/api/employee/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/updateEmployee)
Atualiza um funcionário pelo ID


PUT
[/api/employee/paciente/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/updatePatient)
Atualiza um Paciente


DELETE
[/api/employee/paciente/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/deletePacinet)
Remove um Paciente pelo ID


GET
[/api/employee/doctor/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/getDoctorById)
Obtém um médico pelo ID


PUT
[/api/employee/doctor/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/updateDoctor)
Atualiza um médico pelo ID

GET
[/api/employee/getpaciente/{id}](http://localhost:8080/swagger-ui/index.html#/Employee%20API/getPatientById)
Obtém um Paciente pelo ID

GET
[/api/employee/doctors](http://localhost:8080/swagger-ui/index.html#/Employee%20API/findAllDoctors)
Obtém todos os médicos

não pode retornar o id

![WIN_20241028_18_07_15_Pro](https://github.com/user-attachments/assets/a2922ff3-add8-4ebc-9faf-53ca1a376443)

**Comment by MatheusKSantiago** [comment]
Issue #12 finalizada no commit [e4bcd73fd93ab55c6c37e6a819c1e1b70007f5e3]
